### ISSUE TITLE
server.method doesn't resolve promise with cache options

### ISSUE THREAD

**Issue by tsm91** [hapijs/hapi#3150] opened 2016-05-13 10:33 UTC
You register a server method and that method returns a promise **and** specify caching options as the 3rd argument. The thing dies.

``` js
server.method('test', function () {
  return Promise.resolve('works');
}, {
  // if you remove the cache options it works as expected
  cache: {
    cache: 'redisCache',
    expiresIn: 30 * 1000,
    generateTimeout: 100
  }
});
```

If you omit the `cache` options everything runs great.

Here is a working [gist](https://gist.github.com/tsm91/4cec4cc16048cd3458b17cc3cce5b84a) how to reproduce.

Tested on node `v6.1.0`, `v4.3.0`.

stack trace:

``` sh
Debug: internal, implementation, error
    TypeError: Uncaught error: Cannot read property 'then' of undefined
    at server.route.handler (/Users/tsm/Sites/__projects/hapi-api/reproduce.js:36:7)
    at Object.exports.execute.internals.prerequisites.internals.handler.callback [as handler] (/Users/tsm/Sites/__projects/hapi-api/node_modules/hapi/lib/handler.js:96:36)
    at /Users/tsm/Sites/__projects/hapi-api/node_modules/hapi/lib/handler.js:30:23
    at internals.Protect.run.finish [as run] (/Users/tsm/Sites/__projects/hapi-api/node_modules/hapi/lib/protect.js:64:5)
    at exports.execute.finalize (/Users/tsm/Sites/__projects/hapi-api/node_modules/hapi/lib/handler.js:24:22)
    at each (/Users/tsm/Sites/__projects/hapi-api/node_modules/hapi/lib/request.js:383:16)
    at iterate (/Users/tsm/Sites/__projects/hapi-api/node_modules/hapi/node_modules/items/lib/index.js:36:13)
    at done (/Users/tsm/Sites/__projects/hapi-api/node_modules/hapi/node_modules/items/lib/index.js:28:25)
    at internals.Auth.test.internals.Auth._authenticate (/Users/tsm/Sites/__projects/hapi-api/node_modules/hapi/lib/auth.js:210:16)
    at internals.Auth.test.internals.Auth.authenticate (/Users/tsm/Sites/__projects/hapi-api/node_modules/hapi/lib/auth.js:202:17)
Debug: internal, implementation, error
    TypeError: Cannot read property 'apply' of undefined
    at /Users/tsm/Sites/__projects/hapi-api/node_modules/hapi/node_modules/catbox/node_modules/hoek/lib/index.js:850:21
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickDomainCallback (node.js:423:13)
```

**Comment by matthieusieben** [comment] 2016-05-17 12:58
Same issue here.

This is due to the fact that the provided function is wrapped inside a server cache, but the function exposed (through `server.method`) is not promisifyed when `options.callback === false` and `options.cache` is defined.

@tsm91 You forgot to specify the `callback: false` option in your example.

**Comment by matthieusieben** [comment] 2016-05-17 13:10
@tsm91 You can actually still use your method function, but not as a promise:

```js
server.method('test', function (arg) {
  return Promise.resolve('Hello ' + arg + '!');
}, {
  callback: false,
  cache: {
    // cache options
  }
});
server.method.test('World', function(err, result) {
  // result === 'Hello World!'
});
```
without cache
```js
server.method('test', function (arg) {
  return Promise.resolve('Hello ' + arg + '!');
}, {
  callback: false,
  cache: false
});
server.method.test('World').then(function (result) {
  // result === 'Hello World!'
});
```

**Comment by tsm91** [comment] 2016-05-17 13:20
yeah, that is a boomer. i dont like to mix promises with callbacks

**Comment by matthieusieben** [comment] 2016-05-17 13:28
You can still re-promisify the method:

```js

server.method('test', function (arg1, arg2) {
    return Promise.resolve(arg1 + arg2);
}, {
    cache: true,
    callback: false,
});

var normalized = server.methods.test;
server.methods.test = function () {
    return new Promise(function (resolve, reject) {
        var args = Array.prototype.concat(arguments, function(err, result) {
            if (err) {
                reject(err);
            } else {
                resolve(result);
            }
        });
        normalized.apply(this, args);
    });
}
```

Or, in a more generic way:
```js
server.method('test', function (arg1, arg2) {
    return Promise.resolve(arg1 + arg2);
}, {
    cache: true,
    callback: false,
});

server.methods.test = promisify(server.methods.test);

function promisify(fn) {
    return function () {
        return new Promise(function (resolve, reject) {
            var args = Array.prototype.concat(arguments, function(err, result) {
                if (err) {
                    reject(err);
                } else {
                    resolve(result);
                }
            });
            fn.apply(this, args);
        });
    }
}
```

**Comment by nlf** [comment] 2016-06-10 14:27
this feels like a bug, it should be consistent whether caching is enabled or not

**Comment by devinivy** [comment] 2016-06-10 14:33
The problem is that caching requires callback-style over promises because the callback takes a third argument for TTL.  I guess in the case that a promise is returned, that argument could just be omitted.  But then the promise vs. callback API is asymmetrical, which is a just a different kind of API wart.

**Comment by nlf** [comment] 2016-06-10 14:36
or we could make a breaking change and resolve the promise with an object, or an array (value is the first item, ttl the second), or expose it some other way. there's a lot we can do to make this work in a more consistent manner.

**Comment by tsm91** [comment] 2016-06-21 09:52
@matthieusieben in the end i do not use the `server.method` approach but something like this:

some util file excerpt:
```js
let todoListCache;

export function listTodosCache(req) {
  if (!todoListCache) {
    todoListCache = req.server.cache({
      expiresIn: 60 * 1000,
      generateTimeout: 100,
      segment: '!todoList',
      generateFunc({ user, pageNum, i18n }, next) {
        return listTodos(user, pageNum, i18n)
          .then(todoList => next(null, todoList))
          .catch(err => next(err));
      }
    });
  }

  Promise.promisifyAll(todoListCache);

  return todoListCache;
}
```

controller file excerpt:

```js
handler(req, res) {
    listTodosCache(req)
      .getAsync({
        id: `${req.user.id}-${req.query.pageNum}`,
        user: req.user, pageNum:
        req.query.pageNum,
        i18n: req.i18n
      })
      .then(todos => res(todos))
      .catch(err => res(err));
  },
```

**Comment by steevhise** [comment] 2016-07-27 13:11
This should at least be mentioned in the docs.

**Comment by TangMonk** [comment] 2017-01-13 02:32
+1

**Comment by juanjoLenero** [comment] 2017-07-04 17:00
With the increased acceptance of promises and async/await in nodejs 8 and https://github.com/hapijs/hapi/pull/3486 landing recently, I believe the cache api does feel inconsistent. 

I like the idea that @nlf proposed. Resolving a cached thenable server method with an object/array that contains the the result and its ttl would be more natural. Promise in, Promise out vs Promise in, Cb out.

**Closed** 2017-10-18 06:00 UTC
Labels: bug
