### ISSUE TITLE
Registering Inert. Error: Handler name already exists

### ISSUE THREAD

**Issue by spiralni** [hapijs/hapi#2731] opened 2015-08-23 05:15 UTC
I have a problem when registering Inert, it throws an error Handler name already exists

These are my config:

  "dependencies": {
    "actin": "0.0.1",
    "async": "^1.4.2",
    "bell": "^5.0.1",
    "blipp": "^2.2.1",
    "boom": "^2.8.0",
    "confidence": "^1.2.0",
    "glob": "^5.0.14",
    "glue": "^2.1.1",
    "good": "^6.3.0",
    "hapi-auth-cookie": "^3.0.1",
    "hapi-swagger": "^1.1.0",
    "hoek": "^2.14.0",
    "inert": "^3.0.1",
    "joi": "^6.6.1",
    "lodash": "^3.10.1",
    "mongoose": "^4.1.3",
    "rejoice": "^2.0.1",
    "vision": "^3.0.0",
    "wreck": "^6.1.0"
  }

My full code is :
var Hapi = require('hapi');
var Glue = require('glue');

var internals = {};
internals.manifest = {
    connections: [{
        host: 'localhost',
        port: 8000,
        labels: ['api']
    }],
    plugins: [
        { blipp: [{}] },
        { inert: [{ select: 'api', options: {} }]},
        { vision: [{}] },
        { 'hapi-swagger': [
            { 
                select: 'api' ,
                options: { apiVersion: 1.0 }
            }
        ]},
        { './models': [{ select: 'api', options: {} }] },
        { './controllers': [{ select: 'api', options: {} }] },
        { './routes': [{ select: 'api', options: {} }] }
    ]
};

Glue.compose(internals.manifest, { relativeTo: __dirname }, function (err, server) {

    if (err) {
        console.log('server.register err: ', err);
    }

    server.start(function() {
        console.log('server running at ', server.info.uri);
    });
});

Please your comments.

**Comment by hueniverse** [comment] 2015-08-23 05:31
Duplicate of #2730

**Closed** 2015-08-23 05:31 UTC
