### ISSUE TITLE
Feature: be able to pass select options to server.register when argument is array of objects

### ISSUE THREAD

**Issue by danielb2** [hapijs/hapi#2483] opened 2015-03-28 19:29 UTC
What's being done below isn't currently possible.  Seems currently you have to do another register as part of the callback.   Is there any other way?

Regardless, this would be nice if this were possible.

``` javascript
  server.register([
          { register: Plugin1, options: { select: 'http' }},
          { register: Plugin2, options: { select: 'api' }},
          Plugin3
      ],
      function (err) {
          if (err) {
              console.log('server.register err:', err);
              return callback(err);
          }

          server.start(function() {
              return callback(null, server);
          });
      }
  );
```

**Comment by Marsup** [comment] 2015-03-28 19:48
Duplicate of #2478 ?

**Comment by danielb2** [comment] 2015-03-28 19:51
close enough. I expect the answer to be the same. I have to say it's a convenience thing for sure.  I was thinking about glue too, but had assumed it would work this way only to find out it did not.

When I assume things work and they don't, I usually question if the design is as flexible as it should be.

**Comment by danielb2** [comment] 2015-03-28 21:03
Actually, for glue, how do you load a plugin that's defined locally? The manifest option seems to require a name of the package. So if I have it defined in my lib as something or other, then it's not finding it.

**Comment by Marsup** [comment] 2015-03-28 21:29
With a relative path ?

**Comment by danielb2** [comment] 2015-03-28 22:36
Yeah, i tried that... 
``` javascript
plugins: {
  './authenticate': [{ select: 'http' }]
}
```

**Comment by Marsup** [comment] 2015-03-28 22:43
You can always alias local modules in your package.json if none of the paths work.

**Comment by hueniverse** [comment] 2015-03-29 08:31
This request comes up about once every other month. I still don't think this belongs in core. This API is already as complex as it can be with both registration options and plugin options. Adding support for registration options per plugin along side the per plugin options is just nuts.

This belongs in a utility module.

**Closed by hueniverse** 2015-03-29 08:31 UTC
