### ISSUE TITLE
Eslint cannot find module '@hapi/eslint-plugin-hapi'

### ISSUE THREAD

**Issue by alex3wielki** [hapijs/hapi#4154] opened 2020-09-03 18:41 UTC
#### Support plan

* *is this issue currently blocking your project?* (no):
* *is this issue affecting a production system?* (no):

#### Context

* *node version*: v14.9.0
* *module version*: @hapi/eslint-config-hapi: ^13.0.2/  @hapi/hapi: ^20.0.0
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application, eslint
* *any other relevant information*: eslint: ^7.8.1

#### How can we help?

I'm trying to create a lint config file. Here's what I have so far

```    module.exports = {
        'env': {
            'commonjs': true,
            'es6': true,
            'node': true
        },
        'extends': [
          'eslint:recommended',
          '@hapi/eslint-config-hapi',
          ],
        'globals': {
            'Atomics': 'readonly',
            'SharedArrayBuffer': 'readonly'
        },
        'parserOptions': {
            'ecmaVersion': 2018
        },
        'rules': {
            'indent': [
                'error',
                4
            ],
            'linebreak-style': [
                'error',
                'windows'
            ],
            'quotes': [
                'error',
                'single'
            ],
            'semi': [
                'error',
                'always'
            ]
        }
    };
```
The problem is I'm getting 

```    Error: Failed to load plugin '@hapi/eslint-plugin-hapi' declared in '--config » @hapi/eslint-config-hapi': Cannot find module '@hapi/eslint-plugin-hapi'
    Require stack:
    - C:\Users\aironsid\Documents\tatooify\server\__placeholder__.js
    
    Error: Failed to load plugin '@hapi/eslint-plugin-hapi' declared in '--config » @hapi/eslint-config-hapi': Cannot find module '@hapi/eslint-plugin-hapi'
    Require stack:
    - C:\Users\aironsid\Documents\tatooify\server\__placeholder__.js
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
        at Function.resolve (internal/modules/cjs/helpers.js:94:19)
        at Object.resolve (C:\Users\aironsid\Documents\tatooify\server\node_modules\eslint\lib\shared\relative-module-resolver.js:40:50)
        at ConfigArrayFactory._loadPlugin (C:\Users\aironsid\Documents\tatooify\server\node_modules\eslint\lib\cli-engine\config-array-factory.js:1004:39)
        at C:\Users\aironsid\Documents\tatooify\server\node_modules\eslint\lib\cli-engine\config-array-factory.js:895:33
        at Array.reduce (<anonymous>)
        at ConfigArrayFactory._loadPlugins (C:\Users\aironsid\Documents\tatooify\server\node_modules\eslint\lib\cli-engine\config-array-factory.js:891:22)
        at ConfigArrayFactory._normalizeObjectConfigDataBody (C:\Users\aironsid\Documents\tatooify\server\node_modules\eslint\lib\cli-engine\config-array-factory.js:719:44)
        at _normalizeObjectConfigDataBody.next (<anonymous>)
        at ConfigArrayFactory._normalizeObjectConfigData (C:\Users\aironsid\Documents\tatooify\server\node_modules\eslint\lib\cli-engine\config-array-factory.js:659:20)
    Process finished with exit code -1
```
How do I fix this?

I already tried:
- recreating the eslint file
- reinstalling packages
- removing `yarn.lock`

and yes, I installed the `@hapi/eslint-plugin-hapi` package

Here's my index.js just in case

```
'use strict';

const Hapi = require('@hapi/hapi');

const init = async () => {
  const server = Hapi.server({
    port: 3000,
    host: 'localhost'
  });

  server.route({
    method: 'GET',
    path: '/',
    handler: (request, h) => {
      return 'Hello World!';
    }
  });

  await server.start();
  console.log('Server running on %s', server.info.uri);
};

process.on('unhandledRejection', (err) => {
  console.log(err);
  process.exit(1);
});

init();
```
So as you can see it's really basic for now

**Comment by cjihrig** [comment] 2020-09-04 00:36
I can't reproduce this. I was able to lint your code with the config you provided (after making it runnable code) with all of the same module versions.

Can you provide a fully runnable example. For something like this with several moving pieces, a git repo would be best.

**Comment by alex3wielki** [comment] 2020-09-04 08:12
I made it temporarily public. https://gitlab.com/iron.alex/tatooify-server

**Comment by kanongil** [comment] 2020-09-04 12:34
The `@hapi/eslint-plugin-hapi` package is missing from your `package.json`. See proper instructions here: https://hapi.dev/module/lab/api/?v=23.0.0#linting.

**Comment by cjihrig** [comment] 2020-09-04 13:32
Closing as answered!

**Closed by cjihrig** 2020-09-04 13:32 UTC
Labels: support
