### ISSUE TITLE
Intermittent failure of the 'clears connections on close' test

### ISSUE THREAD

**Issue by dwmkerr** [hapijs/hapi#3503] opened 2017-05-29 16:45 UTC
#### Are you sure this is an issue with hapi or are you just looking for some help?

I have been suffering this intermittent failure for the last few weeks. It is entirely possible however that it is an issue with my environment.

I am currently having a look at #3450 and am seeing the issue regularly.

#### What are you trying to achieve or the steps to reproduce?

A clean checkout followed by a run of the test suite with `npm test` often (perhaps 60% of the time) shows:

![image](https://cloud.githubusercontent.com/assets/1926984/26556909/afdc8b3e-44c7-11e7-8bfe-b0365678b4e7.png)

Repeatedly running the test suite shows this test passing and failing without a pattern I can discern. The message is:

```
Failed tests:

  92) Connection _init() clears connections on close (HTTP):

      actual expected

      10

      Expected 1 to equal specified value

      at server.listener.getConnections (/Users/dave/repos/github/dwmkerr/hapi/test/connection.js:385:43
```

#### Context

* *node version*: v7.5.0
* *hapi version*: https://github.com/hapijs/hapi/commit/b92664d9e4e1a184e7e2d958049af0f065d04f02
* *os*: MacOS, Sierra
* *any other relevant information*:

**Comment by bsommardahl** [comment] 2017-05-30 18:47
I'm having a hard time reproducing this. Originally, I thought my machine was going too fast to make this issue surface. So, I have tried reducing my VM to 256 megs of memory with a single core processor. The tests ran slowly, but they all passed. Can you provide any more info about your environment that I might try on my side?

**Comment by dwmkerr** [comment] 2017-05-31 02:13
Hi @bsommardahl, I wonder if it is actually the other way around, I have brand new MacBook Pro 15", 16GB RAM and top end processor, so I wonder if that might be the issue? I'll spin up a parallels instance and see if the issue disappears, will also take a look under the hood at why the test is failing, it seems to be fairly reproducible

**Comment by jeff-kilbride** [comment] 2017-07-15 06:12
@dwmkerr  I've also seen this recently on a mid-2012 15" MacBook Pro, 16GB RAM, quad-core 2.3GHz i7 processor. For me, the test typically passes, but fails on occasion -- maybe one out of 10-15 times. Any luck figuring it out?

There's also another error I'm seeing consistently, and that's occurring on Travis for the node v4 and v6 versions:

```
Failed tests:

  757) transmission transmit() handles stream errors on the response after the response has been piped (inject):

      Timed out (3000ms) - transmission transmit() handles stream errors on the response after the response has been piped (inject)
```
See #3539.

**Comment by dwmkerr** [comment] 2017-07-16 11:20
I'm not sure yet- but the high spec processor might be an indicator as I think someone else mentioned. I've got a long flight coming up where I'll take a look :)

**Comment by sirgallifrey** [comment] 2017-07-16 18:19
I get 3 errors when I test hapi, not sure if it's related... 

```shell
Test script errors:

Multiple callbacks or thrown errors received in test "Connection ext() onPreResponse cleans unused file stream when response is overridden" (done)
      at runCallback (timers.js:804:20)
      at tryOnImmediate (timers.js:762:5)
      at processImmediate [as _immediateCallback] (timers.js:733:5)

Multiple callbacks or thrown errors received in test "transmission marshal() closes file handlers when not reading file stream" (done)
      at runCallback (timers.js:804:20)
      at tryOnImmediate (timers.js:762:5)
      at processImmediate [as _immediateCallback] (timers.js:733:5)

Multiple callbacks or thrown errors received in test "transmission marshal() closes file handlers when not using a manually open file stream" (done)
      at runCallback (timers.js:804:20)
      at tryOnImmediate (timers.js:762:5)
      at processImmediate [as _immediateCallback] (timers.js:733:5)

There were 3 test script error(s).

Failed tests:

  145) Connection ext() onPreResponse cleans unused file stream when response is overridden:

      spawn lsof ENOENT

      at exports._errnoException (util.js:1026:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
      at onErrorNT (internal/child_process.js:366:16)
      at _combinedTickCallback (internal/process/next_tick.js:102:11)
      at process._tickDomainCallback (internal/process/next_tick.js:198:9)

  725) transmission marshal() closes file handlers when not reading file stream:

      spawn lsof ENOENT

      at exports._errnoException (util.js:1026:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
      at onErrorNT (internal/child_process.js:366:16)
      at _combinedTickCallback (internal/process/next_tick.js:102:11)
      at process._tickDomainCallback (internal/process/next_tick.js:198:9)

  726) transmission marshal() closes file handlers when not using a manually open file stream:

      spawn lsof ENOENT

      at exports._errnoException (util.js:1026:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
      at onErrorNT (internal/child_process.js:366:16)
      at _combinedTickCallback (internal/process/next_tick.js:102:11)
      at process._tickDomainCallback (internal/process/next_tick.js:198:9)

```

hapi 16.4.4
npm 4.6.1
node 8.0.0
OS: Arch Linux x86_64
Kernel: 4.11.2-1-ARCH
RAM: 3206M / 7881M (40%)
CPU: Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz

**Comment by hueniverse** [comment] 2017-08-06 07:11
Still an issue?

**Comment by jeff-kilbride** [comment] 2017-08-08 18:55
@hueniverse  I updated to 16.5.2 and ran the test suite five times. I still got the error below on two of the runs:

![image](https://user-images.githubusercontent.com/14877960/29088792-279989e4-7c2f-11e7-93a9-6a1b54c73abd.png)

**Comment by dwmkerr** [comment] 2017-08-09 04:43
@hueniverse yes still an issue for me, I'm desperate to roll my sleeves up and get into it, but have been ridiculously busy at work. Having the issue open is helpful as I'm getting a little more data, I'm hoping to look at this in force this weekend.

**Comment by hueniverse** [comment] 2017-10-18 05:59
Closing due to lack of progress.

**Closed by hueniverse** 2017-10-18 05:59 UTC
