### ISSUE TITLE
server that uses latest version of good breaks after npm prune --production

### ISSUE THREAD

**Issue by lkptrzk** [hapijs/hapi#2508] opened 2015-04-20 13:26 UTC
When a project uses the latest published versions of hapi and good, the server breaks after running `npm prune --production`.

Fixed by updating good's wreck dependency from 5.4.x to 5.x.x, but seems wrong since some other repo could be doing what good's doing to cause this.

Wreck is listed in npm-shrinkwrap.json as 5.2.0... repro below shows `unbuild wreck@5.2.0`, so probably related to the correct way to fix this, but idk how to fix it (see https://github.com/hapijs/contrib/issues/26)

Repro:

```bash
~ > node --version
v0.10.38
~ > npm --version
1.4.28
~ > npm cache clean
~ > mkdir bug && cd bug
~/bug > echo "{}" > package.json && npm install --save hapi
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
hapi@8.4.0 node_modules/hapi
├── cryptiles@2.0.4
├── peekaboo@1.0.0
├── ammo@1.0.0
├── topo@1.0.2
├── accept@1.0.0
├── items@1.1.0
├── kilt@1.1.1
├── catbox-memory@1.1.1
├── call@2.0.1
├── qs@2.4.0
├── shot@1.4.2
├── boom@2.6.1
├── iron@2.1.2
├── wreck@5.2.0
├── hoek@2.11.1
├── catbox@4.2.2
├── mimos@2.0.2 (mime-db@1.7.0)
├── inert@2.1.4 (lru-cache@2.5.0)
├── joi@6.0.8 (isemail@1.1.1, moment@2.9.0)
├── heavy@3.0.0 (joi@5.1.0)
├── statehood@2.0.0 (joi@5.1.0)
├── vision@2.0.0 (joi@5.1.0)
├── h2o2@4.0.0 (joi@5.1.0)
└── subtext@1.0.2 (content@1.0.1, pez@1.0.0)
~/bug > cat > server.js
var Hapi = require('hapi');
var server = new Hapi.Server();
server.connection({ port: 4200 });
server.start(function (err) { console.log('err: ' + err) });
~/bug > node server.js 
err: undefined
^C~/bug > npm prune --production
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
~/bug > node server.js 
err: undefined
^C~/bug > rm -rf node_modules/ && npm install
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
hapi@8.4.0 node_modules/hapi
├── cryptiles@2.0.4
├── peekaboo@1.0.0
├── ammo@1.0.0
├── topo@1.0.2
├── accept@1.0.0
├── items@1.1.0
├── kilt@1.1.1
├── catbox-memory@1.1.1
├── call@2.0.1
├── qs@2.4.0
├── shot@1.4.2
├── boom@2.6.1
├── iron@2.1.2
├── wreck@5.2.0
├── hoek@2.11.1
├── catbox@4.2.2
├── mimos@2.0.2 (mime-db@1.7.0)
├── inert@2.1.4 (lru-cache@2.5.0)
├── joi@6.0.8 (isemail@1.1.1, moment@2.9.0)
├── heavy@3.0.0 (joi@5.1.0)
├── statehood@2.0.0 (joi@5.1.0)
├── h2o2@4.0.0 (joi@5.1.0)
├── subtext@1.0.2 (content@1.0.1, pez@1.0.0)
└── vision@2.0.0 (joi@5.1.0)
~/bug > npm install --save good
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
good@6.1.0 node_modules/good
├── items@1.1.0
├── traverse@0.6.6
├── hoek@2.12.0
├── wreck@5.4.0 (boom@2.7.1)
└── joi@5.1.0 (topo@1.0.2, isemail@1.1.1, moment@2.10.2)
~/bug > node server.js 
err: undefined
^C~/bug > npm prune --production
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
unbuild wreck@5.2.0
~/bug > node server.js 
 
module.js:340
    throw err;
          ^
Error: Cannot find module 'wreck'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/sledmobile/bug/node_modules/hapi/node_modules/h2o2/lib/index.js:7:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
~/bug > 
```

**Comment by Marsup** [comment] 2015-04-20 13:48
Duplicate of #2474.

**Closed by Marsup** 2015-04-20 13:48 UTC
