### ISSUE TITLE
State autoValue function overwrites existing cookie value

### ISSUE THREAD

**Issue by stuartalexwhitehead** [hapijs/hapi#3831] opened 2018-10-16 23:37 UTC
#### Are you sure this is an issue with the hapi core module or are you just looking for some help?
Yeah—either an issue with hapi core, or a doc issue within API.md.

#### Is this a security related issue?
Nah.

#### What are you trying to achieve or the steps to reproduce?
I’ve been configuring a state `autoValue`.

My goal is this: if the cookie does not exist, it should be set with an automatically generated value. If it does exist, the value should be left as-is.

The documentation in [API.md](https://github.com/hapijs/hapi/blob/7ffd301a3e0499df4c0989bd3aca7498bf314ee3/API.md#-serverstatename-options) describes this option:

> `autoValue` - if present _**and the cookie was not received from the client**_ or explicitly set by the route handler, the cookie is automatically added to the response with the provided value. The value can be a function with signature `async function(request)`

#### What was the result you received?
Using this sample script:

```js
const Hapi = require('hapi');

const server = Hapi.server({
    port: 3000,
    host: 'localhost'
});

server.state('test-cookie', {
    isSecure: false,
    autoValue: async () => `${new Date().getTime()}`,
});

server.route({
    method: 'GET',
    path: '/',
    handler: () => 'Test Cookie',
});

const init = async () => {
    await server.start();
    console.log(`Server running at: ${server.info.uri}`);
};

init();
```

1. First request made without a cookie: a new cookie is set, with value from `autoValue`
2. Second request made with cookie: cookie is overwritten, with value from `autoValue`

<img width="924" alt="screen shot 2018-10-17 at 12 29 13 pm" src="https://user-images.githubusercontent.com/4330008/47053187-599f8d00-d208-11e8-9c20-c431cf267528.png">

<img width="924" alt="screen shot 2018-10-17 at 12 29 22 pm" src="https://user-images.githubusercontent.com/4330008/47053201-658b4f00-d208-11e8-9f02-be4cd643ffd9.png">

#### What did you expect?
1. First request made without a cookie: a new cookie is set, with value from `autoValue`
2. Second request made with cookie: cookie value is left as-is

#### Context

* *node version*: 10.12.0
* *hapi version*: 17.6.0
* *os*: Mac OSX High Sierra (10.13.6)
* *any other relevant information*:

**Comment by kanongil** [comment] 2018-10-17 08:50
While your test is flawed (you need to set `isSecure: false` on the state), the issue is real, and `autoValue` is set, regardless of the client supplied cookie.

**Comment by stuartalexwhitehead** [comment] 2018-10-17 19:29
Ah true! My apologies, I’ve updated the sample for clarity (I originally tested behind an HTTPS proxy).

Thanks for the confirmation. Would you like any help to resolve?

**Comment by kanongil** [comment] 2018-10-23 13:29
A PR with one or more failing test cases is always welcome.

You can also take a stab at fixing the issue. It suspect a fix should be somewhat approachable.

**Comment by dominykas** [comment] 2018-11-17 14:01
Fixed in https://github.com/hapijs/hapi/pull/3879

**Closed** 2019-01-06 03:58 UTC
Labels: bug
