### ISSUE TITLE
hapijs with webpack and ts-loader

### ISSUE THREAD

**Issue by TekTimmy** [hapijs/hapi#4236] opened 2021-03-11 15:17 UTC
#### Support plan

* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*:  v12.21.0
* *module version*: 20.1.0
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): webpack 5.24.4, typescript 4.2.3, ts-loader 8.0.18
* *any other relevant information*:

#### How can we help?

I'm using Hapi in a NodeJS project with Typescript and the compilation with Webpack fails with several errors. I have tried to use the "node-loader" for ".js" which fixes the errors but the compilation won't work.
Any ideas?

The Webpack compilation errors:
```
RROR in ./node_modules/@hapi/catbox/lib/policy.js 53:9
Module parse failed: Unexpected token (53:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| exports = module.exports = internals.Policy = class {
| 
>     rule = null;
|     stats = {
|         sets: 0,
 @ ./node_modules/@hapi/catbox/lib/index.js 4:15-34
 @ ./node_modules/@hapi/hapi/lib/route.js 7:15-38
 @ ./node_modules/@hapi/hapi/lib/server.js 13:14-32
 @ ./node_modules/@hapi/hapi/lib/index.js 3:15-34
 @ ./src/main.ts 5:15-36

ERROR in ./node_modules/@hapi/hapi/lib/auth.js 17:4
Module parse failed: Unexpected character '#' (17:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| exports = module.exports = internals.Auth = class {
| 
>     #core = null;
|     #schemes = {};
|     #strategies = {};
 @ ./node_modules/@hapi/hapi/lib/route.js 12:13-30
 @ ./node_modules/@hapi/hapi/lib/server.js 13:14-32
 @ ./node_modules/@hapi/hapi/lib/index.js 3:15-34
 @ ./src/main.ts 5:15-36

ERROR in ./node_modules/@hapi/hapi/lib/core.js 54:12
Module parse failed: Unexpected token (54:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| exports = module.exports = internals.Core = class {
| 
>     actives = new WeakMap();                                                   // Active requests being processed
|     app = {};
|     auth = new Auth(this);
 @ ./node_modules/@hapi/hapi/lib/server.js 9:13-30
 @ ./node_modules/@hapi/hapi/lib/index.js 3:15-34
 @ ./src/main.ts 5:15-36

ERROR in ./node_modules/@hapi/hapi/lib/ext.js 12:9
Module parse failed: Unexpected token (12:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| exports = module.exports = internals.Ext = class {
| 
>     type = null;
|     nodes = null;
| 
 @ ./node_modules/@hapi/hapi/lib/server.js 11:12-28
 @ ./node_modules/@hapi/hapi/lib/index.js 3:15-34
 @ ./src/main.ts 5:15-36

ERROR in ./node_modules/@hapi/teamwork/lib/index.js 8:4
Module parse failed: Unexpected character '#' (8:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| exports.Team = class {
| 
>     #meetings = null;
|     #count = null;
|     #notes = null;
 @ ./node_modules/@hapi/hapi/lib/server.js 6:17-42
 @ ./node_modules/@hapi/hapi/lib/index.js 3:15-34
 @ ./src/main.ts 5:15-36
```

My Webpack configuration:
```json
{
  "target": "node12.21",
  "devtool": "source-map",
  "resolve": {
    "extensions": [
      ".ts",
      ".js",
      ".json"
    ]
  },
  "externals": {
    "@hapi": "commonjs2 @hapi"
  },
  "optimization": {
    "minimize": false
  },
  "module": {
    "rules": [
      {
        "use": [
          {
            "loader": "ts-loader",
            "options": {}
          }
        ],
        "test": ".ts$"
      }
    ]
  },
  "entry": "./src/main.ts",
  "output": {
    "filename": "main.js"
  }
}
```
tsconfig.json
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./target",
    "charset": "utf-8",
    "target": "es2018",
    "module": "commonjs",
    "moduleResolution": "node",
    "declaration": false,
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "baseUrl": "./"
  }
}
```

**Comment by kanongil** [comment] 2021-03-11 15:28
Webpack is a bundler and should probably not be used with node projects. Typescript has a nice transpiler that should be able to convert your app code into something node understands.

**Comment by Marsup** [comment] 2021-03-11 15:57
You should have included your tsconfig.json as well, this is probably where the problem is.

**Comment by TekTimmy** [comment] 2021-03-11 16:10
> Webpack is a bundler and should probably not be used with node projects. Typescript has a nice transpiler that should be able to convert your app code into something node understands.

Webpack can be used to compile node! The project is in production with a slightly different configuration using pretty outdated libraries, what I have pasted here is the try to make it work with the latest versions of hapi. But you are right, we probably do not need webpack, will consider it, thanks.



> You should have included your tsconfig.json as well, this is probably where the problem is.

I added it ! Thank you

**Comment by Marsup** [comment] 2021-03-11 16:31
IIRC node 12 supports a higher target than es2018, probably at least es2019, to be verified. You should also have a line like `"lib": ["esnext"],` (or the appropriate level you want) in your `compilerOptions` section to support those syntaxes.

There is IMHO no appropriate setting since node always supports EScurrent + some parts of ESnext. I personally usually target esnext so TS barely transpiles anything at all, and then make sure I don't go crazy on features that are not supported natively by node (you need a good coverage for that though).

**Comment by Marsup** [comment] 2021-03-11 16:33
BTW, come to think of it, are you bundling your node_modules into it ? It's usually excluded, that seems weird and dangerous.

**Comment by TekTimmy** [comment] 2021-03-11 16:45
> IIRC node 12 supports a higher target than es2018, probably at least es2019, to be verified. You should also have a line like `"lib": ["esnext"],` (or the appropriate level you want) in your `compilerOptions` section to support those syntaxes.
> 
> There is IMHO no appropriate setting since node always supports EScurrent + some parts of ESnext. I personally usually target esnext so TS barely transpiles anything at all, and then make sure I don't go crazy on features that are not supported natively by node (you need a good coverage for that though).

I just tried some different adjustments of `target` and `lib` in the `tsconfig.json`. Also found this: https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping
But nothing works.

> BTW, come to think of it, are you bundling your node_modules into it ? It's usually excluded, that seems weird and dangerous.

Yes you are right! I'm generating the `externals` value dynamically based on what is in the `node_modules` folder:
```js
function getExternals() {
  const nodeModules = {};
  FS.readdirSync(Path.resolve(__dirname, 'node_modules'))
    .filter(function(x) {
      return ['.bin'].indexOf(x) === -1;
    })
    .forEach(function(mod) {
      nodeModules[mod] = `commonjs2 ${mod}`;
    });

  return nodeModules;
}
```

**Comment by devinivy** [comment] 2021-03-11 17:03
Just because it hasn't been mentioned yet explicitly— your compilation step is struggling with [public/private class field](https://github.com/tc39/proposal-class-fields) syntax.  These were introduced in node v12.  I am not sure whose job it will be to understand those (i.e. typescript or webpack), but if you are running your application on node v12+ then you will not want your compilation/transpilation step to compile them away.  My best guess is that webpack's acorn parser doesn't understand these by default.

**Comment by Marsup** [comment] 2021-03-11 17:09
After thinking about it, my bet would be it's a webpack issue, as ts-loader only cares for *.ts, so playing with tsconfig seems like a dead end. But it seems super dumb to throw an additional babel-loader to take care of a syntax node understands perfectly well.

**Comment by Marsup** [comment] 2021-03-11 17:16
FWIW, you're not alone: https://github.com/webpack/webpack/issues/10216

**Comment by TekTimmy** [comment] 2021-03-11 17:37
> Just because it hasn't been mentioned yet explicitly— your compilation step is struggling with [public/private class field](https://github.com/tc39/proposal-class-fields) syntax. These were introduced in node v12. I am not sure whose job it will be to understand those (i.e. typescript or webpack), but if you are running your application on node v12+ then you will not want your compilation/transpilation step to compile them away. My best guess is that webpack's acorn parser doesn't understand these by default. As Gil mentioned, webpack isn't particularly optimized for use packaging node applications, so you may hit some rough edges.

I understand, thanks for sharing your perspective!

> After thinking about it, my bet would be it's a Webpack issue, as ts-loader only cares for *.ts, so playing with tsconfig seems like a dead end. But it seems super dumb to throw an additional babel-loader to take care of a syntax node understands perfectly well.

Yeah that is dump I agree! Probably makes sense to remove Webpack.. will think about it! The project has ~10 microservices sharing some common classes and a lot of interfaces. So it seemed easiest to compile everything into one with Webpack.

> FWIW, you're not alone: [webpack/webpack#10216](https://github.com/webpack/webpack/issues/10216)

awesome, thank you !

**Comment by Nargonath** [comment] 2021-03-12 17:19
Shouldn't we close the issue since it doesn't seem to be a problem with hapi itself. It doesn't prevent you to keep talking about your problem though. 😉

**Comment by devinivy** [comment] 2021-03-12 19:03
Yeah, that sounds right to me— I don't think there's anything hapi itself can do to help here.  @TekTimmy as Jonas mentioned above, please feel free to continue the discussion!  You also may find some help in our hapi hour Slack, I know there's a #typescript channel in there.  You can find an invite link to hapi hour on the website: https://hapi.dev/support/

**Closed by devinivy** 2021-03-12 19:03 UTC
Labels: support
