### ISSUE TITLE
502 with Cryptiles 3.0.1

### ISSUE THREAD

**Issue by kylebuch8** [hapijs/hapi#3230] opened 2016-07-06 13:25 UTC
When I run npm install --save hapi, I'm getting some 502 errors with the cryptiles package.

npm ERR! fetch failed https://registry.npmjs.org/cryptiles/-/cryptiles-3.0.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502

Should I be logging this issue in the cryptiles repo?

**Comment by Marsup** [comment] 2016-07-06 13:33
This looks more like a npm or proxy issue.

**Comment by devinivy** [comment] 2016-07-06 13:43
I intermittently experience this too, with the same package.  You can actually see it here: https://registry.npmjs.org/cryptiles/-/cryptiles-3.0.1.tgz.  It appears to be an npm issue.

**Comment by DavidTPate** [comment] 2016-07-06 13:46
Weird. I would open an issue with `npm` as it's not something I'm able to reproduce either. I would guess it might have something to do with geographic location.

**Comment by cjihrig** [comment] 2016-07-06 13:49
Could this be related to https://github.com/npm/npm/issues/13284.

**Comment by DavidTPate** [comment] 2016-07-06 14:10
It seems to be. I was curious so I cleared out my `node_modules` and reinstalled. In my case I'm erroring on `lodash.isstring` only for my project. My other modules including `hapi` and the sub-dependencies install as expected.

Seems like this could be closed as it is being tracked already in `npm`

**Closed** 2016-07-06 14:11 UTC
Labels: non-issue

**Comment by AdriVanHoudt** [comment] 2016-07-06 15:02
follow the incident here http://status.npmjs.org/incidents/nl2mpgltpnvj
