### ISSUE TITLE
Error tag incorrectly set

### ISSUE THREAD

**Issue by mfanto** [hapijs/hapi#3898] opened 2019-01-08 18:58 UTC
All requests, including with the `Hello World` tutorial on https://hapijs.com, show the error tag. 

#### Are you sure this is an issue with the hapi core module or are you just looking for some help?

Yes, I believe so. 

#### Is this a security related issue?

No

#### What are you trying to achieve or the steps to reproduce?

Using the following example: https://gist.github.com/mfanto/9ffac7d26a26cd1649c9ff6810be9d73

#### What was the result you received?

```
Debug: request, error, close
{ request: true, error: true, close: true }
Debug: response, error, close
{ response: true, error: true, close: true }
```

The error tag is set to true, both through debugging turned on, as well as the server `request` event. 

#### What did you expect?

The error tag to not be set. 

#### Context

* *node version*: 11.6.0
* *hapi version*: 17.8.1
* *os*: Mac OSX 

I think the problem is with this line: https://github.com/hapijs/hapi/blob/c88bda0d0fd3f269b57229e49083645fb2ddf241/lib/request.js#L593

Regardless if err is truthy or not, it always sets the `error` tag.

**Comment by devinivy** [comment] 2019-01-08 19:22
I can confirm also on hapi v17.7.0 and node v11.2.0.  I can also confirm that the issue _does not_ occur on node v10.12.0 with the same hapi version.  I recall some timer issues in node v11 that @cjihrig experienced and reviewed (i.e. https://github.com/nodejs/node/pull/24322).  While those bugs were fixed in v11.2.0, perhaps there's something else going on in a similar vein.

**Comment by cjihrig** [comment] 2019-01-08 20:04
I don't think this is related to the timers issues (*knocks on wood*).

https://github.com/nodejs/node/pull/20611 landed in Node 10.2.0. If you run the example against Node 10.2.0, you'll see the same output as you see on Node 11. That commit was determined to be a breaking change, and reverted in Node 10.8.0 in https://github.com/nodejs/node/pull/21809, which is when the behavior goes back to what we expect.

https://github.com/nodejs/node/pull/20611 was then re-released in Node 11, which is why we see the different behavior. I think hapi will probably want to update to deal with this.

**Comment by mfanto** [comment] 2019-01-08 21:02
I don't know if this additional information is helpful, but it looks like when running against v10.15.0, I don't see the `request` event fire at all (as shown in my original gist).

**Comment by hueniverse** [comment] 2019-01-15 01:42
v8 and v10 do not have this problem, hence nothing is being reported (the internal request events are only fired on errors). With v11, looks like `close` is now a normal event, not just an error one.

**Closed** 2019-01-15 06:48 UTC
Labels: bug
