### ISSUE TITLE
Tape and server.inject problem

### ISSUE THREAD

**Issue by ArtZanko** [hapijs/hapi#2723] opened 2015-08-17 11:42 UTC
Hello.We are using tape+gulp for testing our hapi server. At first I create a mock:
```javascript
var server;
serverMock(function(obj) {
        server = obj;
        test.end();
    });
```
serverMock is a module
```javascript
var _ = require('lodash');
var Hapi = require('hapi');
var config = require('../../config');
var cacheMock = require('./cache');

module.exports = function(done) {
    var server = new Hapi.Server();

    server.connection();

    server.route(require('../../server/routes'));

    var cache = server.cache({segment: 'first', expiresIn: config.cache.expiresIn});
    cache._cache.start(_.noop); 

    var methods = require('../../server/methods');

    server.method('first.cache', methods.cache, {bind: cache});
    server.method('first.get', methods.get, {bind: cache});

    cache.set(cacheMock.id, cacheMock);

    server.start(function() {
        return done(server);
    });
};
```
Then test is passing. And at the end:
```javascript
server.stop();
```
I want to notice that all tape.end() functions is called but process still alive. I think its because server keep it alive. Maybe you can help me..

**Comment by hueniverse** [comment] 2015-08-18 17:01
You might want to give `stop()` a timeout option.

**Comment by ArtZanko** [comment] 2015-08-18 17:07
Yes I did. Still doesn't work.

**Comment by hueniverse** [comment] 2015-08-18 17:13
No idea. You can try to run the code without the testing setup just to make sure as a standalone app it runs and exits correctly.

**Comment by ArtZanko** [comment] 2015-08-18 17:29
I tried to call server.stop in app without tesing setup and nothing happened(only stop callback was called but a process was alive).. Function server.stop should make a process exit, right?

**Comment by tthyer** [comment] 2015-08-18 17:59
I had a similar problem using tape with hapi caching. I attempted using a timeout with stop, not starting the server and instead starting and stopping the cache itself, but still the test did not complete. I tracked the problem down to the timer set by Catbox-Memory and cleared it:
`clearTimeout(server._caches._default.client.connection.cache['segmentName']['keyName'].timeoutId)`
Then my test would complete.

Checking catbox-memory commits, it looks like there's a fix for this in master that hasn't been released yet.

**Comment by hueniverse** [comment] 2015-08-18 18:55
@cjihrig what's the status of the catbox-memory fix?

**Comment by cjihrig** [comment] 2015-08-18 19:21
I'll do a release right now.

**Comment by cjihrig** [comment] 2015-08-18 19:32
@tthyer I just released v1.1.2 of catbox-memory. Care to give it a shot?

**Comment by tthyer** [comment] 2015-08-18 20:32
Just confirmed that this works. Thanks! 
@ArtZanko I used catbox-memory v1.1.2 as my cache engine, called server.stop and the tape test completed.

**Comment by hueniverse** [comment] 2015-08-18 22:45
@cjihrig can you PR to update hapi with the new version

**Comment by cjihrig** [comment] 2015-08-18 23:05
Sure thing

**Comment by ArtZanko** [comment] 2015-08-19 03:23
Yes it works! Thank you very much!
One more question. When i call npm install hapi it install catbox-memory 1.1.1 as dependency I have to call npm update catbox-memory in hapi directory to update it. How to get catbox-memory latest version with just calling npm install in app directory?
Thanks once again!

**Closed** 2015-08-19 06:58 UTC
Labels: bug
