### ISSUE TITLE
Catbox  catbox-memory throws an error but it is not handled properly 

### ISSUE THREAD

**Issue by Ashik155** [hapijs/hapi#4484] opened 2024-03-08 01:02 UTC
### Runtime

node

### Runtime version

14.15

### Module version

catbox - 10.2.3, catbox-memory 4.1.1, hapi 18. 4.0

### Used with

catbox, catbox-memory

### Any other relevant information

 going down the stacktrace, the implementatio, from catbox-memory identifies the cache limit size, but doesn't handle it, and upstream all the way to catbox itself it's not handled, nor in the hapi request cycle
 
 Cache size limit reached, stack: Error: Cache size limit reached\n    at module.exports.internals.Connection.set (/opt/bba/server/node_modules/@hapi/catbox-memory/lib/index.js:184:19)\n    at module.exports.set (/opt/bba/server/node_modules/@hapi/catbox/lib/client.js:91:31)\n    at module.exports.internals.Policy.set (/opt/bba/server/node_modules/@hapi/catbox/lib/policy.js:298:31)\n    at internals.onPreResponse (/opt/bba/server/node_modules/@hapi/yar/lib/index.js:307:17)\n    at async module.exports.internals.Manager.execute (/opt/bba/server/node_modules/@hapi/hapi/lib/toolkit.js:45:28)\n    at async Request._invoke (/opt/bba/server/node_modules/@hapi/hapi/lib/request.js:339:30)\n    at async Request._postCycle (/opt/bba/server/node_modules/@hapi/hapi/lib/request.js:402:32)\n    at async Request._reply (/opt/bba/server/node_modules/@hapi/hapi/lib/request.js:381:9)\n"}

### How can we help?
 how can the this be resolved or error can be handled.

`const serverDev = Hapi.server({
    debug: { request: ['error', 'request', 'response'] },
    host:   <PRIVATEHOST>
    port: <PORT>
    routes: {
        cors: {
      
            ],
            //headers: ["Accept", "Content-Type"],
            //additionalHeaders: ["X-Requested-With"],
        },
        validate: {
            failAction: errorHandler.handleError,
        },
        timeout: {
            server: 60000 * 2, // ms
            socket: 60000 * 3, // ms
        },
    },
    cache: {
        name: '_default_',
        provider: {
            constructor: CatboxMemory,
            options: {
                maxByteSize: 524288000,
            },
        },
    },
});`

**Comment by Marsup** [comment] 2024-03-11 19:33
Dupe of https://github.com/hapijs/catbox-memory/issues/89.

**Closed by Marsup** 2024-03-11 19:33 UTC
Labels: support
