### ISSUE TITLE
Memory leak when passing undefined lifecycle handler

### ISSUE THREAD

**Issue by RichPMad** [hapijs/hapi#4343] opened 2022-03-17 16:27 UTC
#### Support plan

* *is this issue currently blocking your project?* (yes/no): No
* *is this issue affecting a production system?* (yes/no): Yes

#### Context

* *node version*: v16.13.2
* *module version with issue*: "@hapi/hapi": "^20.2.1"
* *last module version without issue*: ??
* *environment* (e.g. node, browser, native): node
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*: -

#### What are you trying to achieve or the steps to reproduce?

Hi, I've found a way to trigger a memory leak, by passing an undefined value to a lifecycle hook such as `onPreAuth`. Hapi does not trigger any validation for `server.ext('onPreAuth', UNDEFINED_FN)`.

Passing an undefined value causes hapi to hold on to the request and response objects.

See my example here: https://github.com/RichPMad/hapi-memory-leak-undefined-lifecycle-fn 

#### What was the result you got?

`Request` and `Response` objects are not cleared from memory. No warnings are given, and no validation errors happen when setting up lifecycle hook.

#### What result did you expect?

Lifecycle hooks warn me I'm being dumb and accidentally passing an undefined value.

**Comment by devinivy** [comment] 2022-03-17 16:52
Hey!  I understand the confusion here, but I think you're running into intentional behavior of the framework.  When you don't pass a method to `server.ext()`, it returns a promise that will resolve with the `request` the next time the extension is invoked.  It's possible that letting these promises hang out could be the cause of a memory leak, though this API is primarily to help make testing more convenient.

Here's the section of the docs: https://hapi.dev/api/#-serverextevent-method-options
> The method may be omitted (if options isn't present) or passed null which will cause the function to return a promise. The promise is resolved with the request object on the first invocation of the extension point. This is primarily used for writing tests without having to write custom handlers just to handle a single event.

Here's a backing test for the behavior: https://github.com/hapijs/hapi/blob/2f80e843d9527c46d5f1ca85e9697e846b65a72b/test/server.js#L1006-L1015

Sorry for any confusion that may have caused!  If you want to ensure you never run into this, you can use `server.ext({ event, method })` instead of `server.ext(event, method)` 👍

**Comment by RichPMad** [comment] 2022-03-17 17:07
Thanks for the quick response!

Oh wow, I see, sorry I glossed over the docs on this one. 

That's pretty tricky 😄 This might be the first time I didn't expect some behavior from hapi. I will certainly use the object syntax instead, thanks for the support.

**Comment by kanongil** [comment] 2022-03-18 11:53
FYI, it is complicated to distinguish passing `undefined`, vs. omitting the argument (unless you use the controversial `arguments.length` property).

It would have to look something like this:
```js
ext(events, ...args) {

     const [method, options] = args;

     Hoek.assert(args.length === 0 || typeof method === 'function', 'Method must be a function');

     // regular logic...
}
```

But that breaks the current API, which allows it to be `null`/`undefined` while still passing `options` and returning a promise.

Given your case, it might be worth to change the API to always throw an error when a `function` is not passed.

**Comment by devinivy** [comment] 2022-04-20 02:40
I believe this was resolved by https://github.com/hapijs/hapi/pull/4345.

**Closed by devinivy** 2022-04-20 02:40 UTC
Labels: support
