### ISSUE TITLE
How to get header(Authorization) and pass it as a userID

### ISSUE THREAD

**Issue by ashrafmangalore** [hapijs/hapi#3564] opened 2017-08-23 09:53 UTC
Hi, Can we get header(authorization) and insert it as a userId?

Here is my code
   
    const ratingSchema = Joi.object().keys({
          ratings: Joi.number().precision(2),
          comment_added: Joi.date().timestamp('javascript').default(() => Date(new Date()), 'creation date'),
          commentId: Joi.number().integer().default(new Date().getTime().toString())    
    });`

    
    const schemas = {        
        createReviews: {
                 headers: {
                 authorization: Joi.string().required()
                 },
                params: {
                    Id: Joi.string().regex(/^[A-Fa-f0-9]{24}$/).required()
                },
                body: {
                    comment_added: Joi.date().timestamp('javascript').default(() => Date(new Date()), 'creation date'),
                    commentId: Joi.number().integer().default(new Date().getTime().toString()),
                    userId:  ? (Here I want to take authorization and it should auto insert. Can you please tell How can I do it?)
               }   
       }
    };`

#### What did you expect ?
in **userId** I want to take authorization key and insert it as a userId. Please tell me How can I do it

**Comment by Marsup** [comment] 2017-08-23 10:18
Don't spam projects. Duplicate of https://github.com/hapijs/joi/issues/1280.

**Closed by Marsup** 2017-08-23 10:19 UTC
