### ISSUE TITLE
Promises on prerequisites makes handler to swallow exceptions

### ISSUE THREAD

**Issue by dmacosta** [hapijs/hapi#2771] opened 2015-09-17 17:48 UTC
I've this issue when using `Promises` on a prerequisite handler and throwing an error from a handler.

```javascript
var Promise = require('promise');


exports.register = function (server, options, next) {

    var pre = function (request, reply) {

        return reply(Promise.resolve('value'));
    };

    server.route({
        method: 'GET',
        path: '/bar',
        config: {
            pre: [
                { method: pre, assign: 'pre' }
            ],
            handler: function (request, reply) {

                // throws here will get swallowed

                throw new Error('will timeout');
                return reply();
            }
        }
    });

    return next();
};

exports.register.attributes = {
    pkg: require('./package.json')
};
``` 

Replying with a literal value on the `pre()` does it make it work. Using Promises on the handler will too, but it sounds more like a workaround to me.

Here's the dependencies I'm using:

```
code@1.5.0 node_modules/code
└── hoek@2.16.2

promise@7.0.4 node_modules/promise
└── asap@2.0.3

hapi@9.3.1 node_modules/hapi
├── ammo@1.0.1
├── cryptiles@2.0.4
├── topo@1.0.3
├── peekaboo@1.0.0
├── items@1.1.0
├── kilt@1.1.1
├── catbox-memory@1.1.2
├── accept@1.1.0
├── call@2.0.2
├── statehood@2.1.1
├── boom@2.8.0
├── iron@2.1.3
├── shot@1.6.0
├── qs@4.0.0
├── hoek@2.14.0
├── catbox@6.0.0
├── mimos@2.0.2 (mime-db@1.18.0)
├── subtext@2.0.0 (content@1.0.2, wreck@6.1.0, pez@1.0.0)
├── joi@6.6.1 (isemail@1.1.1, moment@2.10.6)
└── heavy@3.0.0 (joi@5.1.0)

lab@5.17.0 node_modules/lab
├── diff@1.4.0
├── items@1.1.1
├── json-stringify-safe@5.0.1
├── bossy@1.0.3
├── eslint-config-hapi@2.0.1
├── hoek@2.16.2
├── espree@2.2.5
├── mkdirp@0.5.1 (minimist@0.0.8)
├── source-map-support@0.3.2 (source-map@0.1.32)
├── jslint@0.9.3 (exit@0.1.2, nopt@3.0.4, readable-stream@1.0.33, glob@4.5.3)
├── handlebars@4.0.2 (async@1.4.2, source-map@0.4.4, optimist@0.6.1, uglify-js@2.4.24)
├── eslint@1.4.3 (escape-string-regexp@1.0.3, object-assign@2.1.1, path-is-absolute@1.0.0, path-is-inside@1.0.1, xml-escape@1.0.0, user-home@1.1.1, strip-json-comments@1.0.4, estraverse-fb@1.3.1, globals@8.8.0, estraverse@4.1.0, text-table@0.2.0, is-resolvable@1.0.0, shelljs@0.3.0, debug@2.2.0, glob@5.0.14, chalk@1.1.1, optionator@0.5.0, lodash.merge@3.3.2, lodash.clonedeep@3.0.2, lodash.omit@3.1.0, doctrine@0.6.4, minimatch@2.0.10, concat-stream@1.5.0, is-my-json-valid@2.12.2, to-double-quotes@1.0.1, to-single-quotes@1.0.3, file-entry-cache@1.2.3, inquirer@0.9.0, js-yaml@3.4.2, escope@3.2.0)
└── eslint-plugin-hapi@1.2.0 (hapi-scope-start@1.1.2, hapi-capitalize-modules@1.1.1, no-shadow-relaxed@1.0.1)
```

I can upload an small repo with a few tests if it helps.

**Comment by devinivy** [comment] 2015-09-17 17:53
I've experienced something like this too while playing around. Possibly related to https://github.com/hapijs/discuss/issues/155.

**Comment by hueniverse** [comment] 2015-09-17 17:54
Since I don't use promises I can't really help you. Maybe someone who knows promises well can look into it. I'll leave this open for a bit.

**Comment by devinivy** [comment] 2015-09-17 18:05
@dmacosta if you put a repo up with some tests, I'll definitely take a peek.

**Comment by nlf** [comment] 2015-09-17 18:08
my gut says this is because of domains. likely something is causing the request handler's domain to get lost.

**Comment by nlf** [comment] 2015-09-17 18:19
@devinivy i'm online in gitter if you want a second pair of eyes on this when you get around to checking it out

**Comment by dmacosta** [comment] 2015-09-17 18:19
@devinivy @nlf https://github.com/dmacosta/hapi-issue-2771

**Comment by nlf** [comment] 2015-09-17 18:46
confirmed this is a domains issue, i think i have a fix

**Comment by nlf** [comment] 2015-09-17 19:46
ok, i don't have a fix, but i can definitely confirm it's an issue with domains..

adding logging to the error handler in `lib/protect.js` reveals the error isn't caught at all. logging `process.domain` within the handler that is run after a normal prerequisite gives a domain object, however in a handler that is run after a prerequisite that returns a promise, it's undefined.

that's as far as i got. promises are hard.

**Comment by devinivy** [comment] 2015-09-17 20:00
Yeah, I spent about 15mins with this and didn't get far at all.  The promise library used (https://github.com/then/promise) does have a note about domains in the README worth looking at.

**Comment by hueniverse** [comment] 2015-09-25 15:32
I'm going to label this as a bug but close it because we can't do anything about these issues. I am going to add a domains-free option soon.

**Closed** 2015-09-25 15:33 UTC
Labels: bug

**Comment by devinivy** [comment] 2015-09-25 15:50
Worth adding that I revisited this.  The "done" handler that hapi calls for the promise escapes the domain (i.e., `onDone` in `promiseFromPre.then(onDone, onDone)`), but there was no way I could fix it.  Different promise libraries behaved slightly differently, too.  The promise library used in this particular example looks like it executes the callbacks outside a domain intentionally via the `asap` module.

**Comment by hueniverse** [comment] 2015-10-01 23:17
You can now try turning off domains if you want.

**Comment by rubennorte** [comment] 2017-05-19 14:00
I ended up in this issue after loosing the active domain in my handlers. After some investigation I tested replacing native promises with Bluebird and it works fine.

I created a gist with examples of this behaviour in case it helps someone: https://gist.github.com/rubennorte/f10d2f6ec376b28589a98bb17ef6ae85

**Comment by kanongil** [comment] 2017-05-20 18:01
Node will support domain bindings for promises, which has already been implemented in the master branch, see https://github.com/nodejs/node/pull/12489.
