### ISSUE TITLE
Default authentication scheme not respected by Hapi 15.0.1+

### ISSUE THREAD

**Issue by gordysc** [hapijs/hapi#3329] opened 2016-08-31 07:37 UTC
We've upgraded Hapi from 14.2.0 to 15.0.1 and noticed our default authentication scheme is no longer being respected.  I've attached the auth strategy and route definition below that reproduces this issue on Hapi 15.0.1 (this works on Hapi 14.2.0)

**Auth strategy definition**
```js
server.register(require('hapi-auth-cookie'), (err) => {
    Hoek.assert(!err, err)
    server.auth.strategy('session', 'cookie', true, {
      password: process.env.COOKIE_PASSWORD,
      cookie: 'session',
      isSecure: (process.env.NODE_ENV === 'production'),
      validateFunc: (request, session, callback) => {
        if (!session || !session.id) return callback(null, false)
        server.app.cache.get(session.id, (err, cached) => {
          if (err) return callback(err, false)
          if (!cached || !cached.user) return callback(null, false)
          return callback(null, true, cached.user)
        })
      }
    })
  })
```
**Route definition**
```js
  server.route({
    method: 'POST',
    path,
    config: {
      auth: {
        mode: 'try'
      }
    },
    handler (request, reply) {
      return reply()
    }
  })
```
**Error Stack Trace**
```js
Error: Route missing authentication strategy and no default defined: /sessions
    at Object.exports.assert (/usr/src/app/node_modules/hoek/lib/index.js:736:11)
    at internals.Auth._setupRoute (/usr/src/app/node_modules/hapi/lib/auth.js:112:14)
    at new module.exports.internals.Route (/usr/src/app/node_modules/hapi/lib/route.js:159:72)
    at internals.Connection._addRoute (/usr/src/app/node_modules/hapi/lib/connection.js:412:19)
    at internals.Connection._route (/usr/src/app/node_modules/hapi/lib/connection.js:404:18)
    at internals.Plugin._apply (/usr/src/app/node_modules/hapi/lib/plugin.js:587:14)
    at internals.Plugin.route (/usr/src/app/node_modules/hapi/lib/plugin.js:557:10)
    at Object.exports.register (/usr/src/app/src/routes/sessions/post.js:6:10)
    at Object.target [as register] (/usr/src/app/node_modules/joi/lib/object.js:77:34)
    at each (/usr/src/app/node_modules/hapi/lib/plugin.js:317:14)
```

This is running on [Node 6.5 using the slim Docker image](https://github.com/nodejs/docker-node/blob/910443c39c80291f0bf24712d8d94279cf15b7b5/6.5/slim/Dockerfile)

**Comment by Marsup** [comment] 2016-08-31 07:52
Probably a dupe of https://github.com/hapijs/discuss/issues/349.

**Closed by Marsup** 2016-08-31 07:52 UTC
Labels: non-issue

**Comment by gordysc** [comment] 2016-08-31 09:08
Yup, next time I'll RTFM... thanks for the pointer!
